USE DATABASE PORTFOLIO_DB;
USE SCHEMA INGESTION;

-- Upload sample_data/employee_sample.txt to the internal stage first.
LIST @PORTFOLIO_DB.INGESTION.CHARSEQ_STAGE;

CALL PORTFOLIO_DB.INGESTION.LOAD_CHARACTER_SEQUENCE_FILE(
    'employee_sample.txt',
    'EMPLOYEE_SAMPLE'
);

SELECT *
FROM PORTFOLIO_DB.INGESTION."EMPLOYEE_SAMPLE"
ORDER BY "EmployeeID";
